### ISSUE TITLE
Explique ton code

### ISSUE THREAD

**Issue by JeffAbrahamson** [Rock3f/Exercice-Machine-Learning#1]
Suggestion générale : commente ton code et organise en fonction.  Utilise pylint.

https://stackoverflow.com/questions/356161/python-coding-standards-best-practices#356238

En outre, utilise quelque chose comme ceci :

```
def main():
    """...
    """

if __name__ == "__main__":
    main()
```

**Comment by Rock3f** [comment]
Les modifications sont en place.
